#!/usr/bin/env python3
"""Build a symbol graph of this repository, so a question about the code can be
answered by locating a symbol rather than by reading whole files.

Why this exists
---------------
The tree is ~122k lines across ~196 files, and single files reach 14k lines.
Answering "where is X, who calls it, what does it call" by reading source costs
more context than the answer is worth, and the cost is paid again after every
compaction and in every new session.

This emits a compact index instead:

    symbols.jsonl   one line per definition: name, kind, file, line, signature
    edges.jsonl     caller -> callee, by name
    files.jsonl     file -> crate, line count, symbol count

Honesty about what this is
--------------------------
It is a LOCATOR, not an authority. Extraction is regex-based, so:

  * a call edge is a NAME match, not a resolved binding - two functions with
    one name produce edges to both, and a method call on a variable is
    attributed by name alone;
  * a symbol inside a macro body or generated by one is missed;
  * a signature is the source line, not a parsed type.

So the contract is: the graph tells you WHERE to look, and you then read those
exact lines before asserting anything about behaviour. That is cheaper than
grepping a 14k-line file and, unlike memory, it cannot drift from the code
because it is regenerated from the code.

Usage:  python scripts/codegraph.py [--out <dir>]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

SKIP_DIRS = {
    "node_modules", "target", "dist", "dist-web", ".git", "gen",
    "__pycache__", ".duckle", "build",
}
ROOTS = ["crates", "apps", "frontend/src", "scripts"]

# ---- Rust ----------------------------------------------------------------

RUST = [
    # (kind, regex). The name group must be called `n`.
    ("fn", re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?(?:async\s+)?(?:unsafe\s+)?(?:extern\s+\"[^\"]+\"\s+)?fn\s+(?P<n>\w+)")),
    ("struct", re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?struct\s+(?P<n>\w+)")),
    ("enum", re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?enum\s+(?P<n>\w+)")),
    ("trait", re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?trait\s+(?P<n>\w+)")),
    ("impl", re.compile(r"^\s*impl(?:\s*<[^>]*>)?\s+(?:(?P<tr>[\w:]+)\s+for\s+)?(?P<n>[\w:]+)")),
    ("mod", re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?mod\s+(?P<n>\w+)")),
    ("macro", re.compile(r"^\s*macro_rules!\s+(?P<n>\w+)")),
    ("const", re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?(?:static|const)\s+(?P<n>[A-Z_][A-Z0-9_]*)")),
]

# ---- TypeScript / TSX ----------------------------------------------------

TS = [
    ("fn", re.compile(r"^\s*(?:export\s+)?(?:default\s+)?(?:async\s+)?function\s+(?P<n>\w+)")),
    ("fn", re.compile(r"^\s*(?:export\s+)?const\s+(?P<n>\w+)\s*(?::[^=]+)?=\s*(?:async\s*)?(?:\([^)]*\)|\w+)\s*(?::[^=]*)?=>")),
    ("type", re.compile(r"^\s*(?:export\s+)?type\s+(?P<n>\w+)")),
    ("type", re.compile(r"^\s*(?:export\s+)?interface\s+(?P<n>\w+)")),
    ("const", re.compile(r"^\s*(?:export\s+)?const\s+(?P<n>[A-Z_][A-Z0-9_]*)\s*[:=]")),
    ("class", re.compile(r"^\s*(?:export\s+)?(?:default\s+)?class\s+(?P<n>\w+)")),
]

DOC_RS = re.compile(r"^\s*///\s?(.*)")
DOC_TS = re.compile(r"^\s*(?:\*|//)\s?(.*)")
CALL = re.compile(r"\b([A-Za-z_]\w{2,})\s*\(")
# Words that look like calls but are not worth an edge.
NOISE = {
    "if", "for", "while", "match", "return", "fn", "let", "else", "switch",
    "catch", "function", "print", "println", "eprintln", "format", "write",
    "assert", "assert_eq", "assert_ne", "vec", "json", "Some", "Ok", "Err",
    "None", "String", "Vec", "Box", "Arc", "Rc", "typeof", "await", "new",
    "require", "import", "export", "const", "super", "this", "self",
}


def crate_of(path: str) -> str:
    parts = path.replace("\\", "/").split("/")
    if parts[0] == "crates" and len(parts) > 1:
        return parts[1]
    if parts[0] == "apps" and len(parts) > 1:
        return "app:" + parts[1]
    if parts[0] == "frontend":
        return "frontend"
    return parts[0]


def walk() -> list[str]:
    out = []
    for root in ROOTS:
        if not os.path.isdir(root):
            continue
        for dp, dn, fn in os.walk(root):
            dn[:] = [d for d in dn if d not in SKIP_DIRS]
            for f in fn:
                if os.path.splitext(f)[1] in (".rs", ".ts", ".tsx", ".py"):
                    out.append(os.path.join(dp, f).replace("\\", "/"))
    return sorted(out)


def doc_above(lines: list[str], i: int, rust: bool) -> str:
    """The last line of the doc comment directly above a definition."""
    pat = DOC_RS if rust else DOC_TS
    best = ""
    j = i - 1
    seen = 0
    while j >= 0 and seen < 12:
        s = lines[j]
        if not s.strip():
            break
        m = pat.match(s)
        if m:
            text = m.group(1).strip()
            if text and not text.startswith("/") and text not in ("*/", "/**"):
                best = text
                # keep walking up: we want the FIRST line of the block
        elif s.strip().startswith(("#[", "@", "/**", "*/")):
            pass  # attributes and comment delimiters do not end the block
        else:
            break
        j -= 1
        seen += 1
    return best[:160]


def extract(path: str):
    try:
        lines = open(path, encoding="utf-8", errors="replace").read().split("\n")
    except OSError:
        return [], []
    rust = path.endswith(".rs")
    pats = RUST if rust else TS
    if path.endswith(".py"):
        pats = [("fn", re.compile(r"^\s*def\s+(?P<n>\w+)")),
                ("class", re.compile(r"^\s*class\s+(?P<n>\w+)"))]

    syms = []
    for i, line in enumerate(lines):
        if len(line) > 400:
            continue
        for kind, pat in pats:
            m = pat.match(line)
            if not m:
                continue
            name = m.group("n")
            if not name or name in NOISE:
                continue
            entry = {
                "n": name,
                "k": kind,
                "f": path,
                "l": i + 1,
                "s": line.strip()[:200],
            }
            if kind == "impl":
                tr = m.groupdict().get("tr")
                if tr:
                    entry["s"] = f"impl {tr} for {name}"
            d = doc_above(lines, i, rust)
            if d:
                entry["d"] = d
            # Mark the things worth finding fast.
            flags = []
            if i > 0:
                prev = "\n".join(lines[max(0, i - 3):i])
                if "#[test]" in prev:
                    flags.append("test")
                if "#[tauri::command]" in prev:
                    flags.append("cmd")
            if flags:
                entry["x"] = flags
            syms.append(entry)
            break

    # Call edges, attributed to the nearest preceding definition in the file.
    names = [(s["l"], s["n"]) for s in syms if s["k"] in ("fn", "impl")]
    edges = []
    if names:
        idx = 0
        current = names[0][1]
        for i, line in enumerate(lines, start=1):
            while idx + 1 < len(names) and names[idx + 1][0] <= i:
                idx += 1
                current = names[idx][1]
            if line.lstrip().startswith(("//", "///", "*", "#")):
                continue
            for callee in CALL.findall(line):
                if callee in NOISE or callee == current:
                    continue
                edges.append((current, callee, path, i))
    return syms, edges


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="codegraph")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    files = walk()
    all_syms, all_edges, file_rows = [], [], []
    for p in files:
        syms, edges = extract(p)
        all_syms.extend(syms)
        all_edges.extend(edges)
        try:
            n = sum(1 for _ in open(p, encoding="utf-8", errors="replace"))
        except OSError:
            n = 0
        file_rows.append({"f": p, "c": crate_of(p), "lines": n, "syms": len(syms)})

    # Only keep edges whose callee is something we actually indexed: an edge to
    # a name we have never defined is noise, not knowledge.
    known = {s["n"] for s in all_syms}
    kept = [e for e in all_edges if e[1] in known]

    with open(os.path.join(args.out, "symbols.jsonl"), "w", encoding="utf-8") as fh:
        for s in all_syms:
            fh.write(json.dumps(s, separators=(",", ":")) + "\n")
    with open(os.path.join(args.out, "edges.jsonl"), "w", encoding="utf-8") as fh:
        for a, b, p, l in kept:
            fh.write(json.dumps({"a": a, "b": b, "f": p, "l": l}, separators=(",", ":")) + "\n")
    with open(os.path.join(args.out, "files.jsonl"), "w", encoding="utf-8") as fh:
        for r in file_rows:
            fh.write(json.dumps(r, separators=(",", ":")) + "\n")

    print(f"files   {len(file_rows)}")
    print(f"symbols {len(all_syms)}")
    print(f"edges   {len(kept)} (of {len(all_edges)} raw; unknown callees dropped)")
    for name in ("symbols.jsonl", "edges.jsonl", "files.jsonl"):
        p = os.path.join(args.out, name)
        print(f"  {name:14s} {os.path.getsize(p)/1024:8.1f} KiB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
